version: "3.9"

services:
  db:
    image: mysql:8
    container_name: market-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: marketdb
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    image: govordin/market-api:latest
    container_name: market-api
    restart: always
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "server=db;database=marketdb;user=root;password=Password"
      Fintacharts__BaseUrl: "https://platform.fintacharts.com"
      Fintacharts__Realm: "fintatech"
      Fintacharts__Username: "r_test@fintatech.com"
      Fintacharts__Password: "kisfiz-vUnvy9-sopnyv"
      Fintacharts__ClientId: "app-cli"
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbdata:
